cvm-version: 0.0.28
ovmf-version: 0.0.2
cpus: 8
memory: 40960

shim:
  domains:
    - df-demo.model.tinfoil.sh
  listen-port: 443
  upstream-port: 8080
  paths:
    - /analyze
    - /health
  origins:
    - https://tinfoil.sh

containers:
  - name: "df-demo"
    image: "ghcr.io/tinfoilsh/df-demo:latest"
